export ZSH=/home/matklad/.oh-my-zsh
ZSH_THEME="candy"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=6"

source $ZSH/oh-my-zsh.sh
source $HOME/.profile
