[package]
name = ""
description = ""
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = ""
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[workspace]
members = ["xtask"]

exclude = [".github/", "bors.toml", "rustfmt.toml"]
